#!/bin/bash

INTERNAL=eDP1
EXTERNAL=DP1

if xrandr | grep "$EXTERNAL disconnected"; then
  xrandr --output "$EXTERNAL" --off --output "$INTERNAL" --auto
else
  xrandr --output "$INTERNAL" --off --output "$EXTERNAL" --auto
fi
